---
controller_hostname: "{{ groups['controller_hosts'][0] }}"
keystone_api_url: http://{{ controller_hostname }}:5000
memcached_servers_url: "{{ controller_hostname }}:11211"
database_user: root
database_pass: overrideme
database_host: "{{ hostvars[groups['controller_hosts'][0]]['ansible_facts'][management_interface]['ipv4']['address'] }}"
database_dir: /var/lib/mysql
database_socket: "{{ _database_socket[ansible_os_family] }}"
_database_socket:
  Debian: /var/run/mysqld/mysqld.sock
  RedHat: /var/lib/mysql/mysql.sock
neutron_user: neutron
neutron_pass: password123
neutron_group: neutron
neutron_database: neutron
neutron_database_user: neutron
neutron_database_pass: PLACEMENT_DBPASS
neutron_database_privs: '*.*:ALL'
neutron_database_provider: fernet
neutron_packages:
- openstack-neutron
- openstack-neutron-ml2
- openstack-neutron-linuxbridge
- ebtables
neutron_core_plugin: ml2
neutron_service_plugins: router
neutron_allow_overlapping_ips: true

neutron_metadata_proxy_shared_secret: METADATA_SECRET
neutron_service_metadata_proxy: true

keystone_auth_url: 'http://{{ controller_hostname }}:5000/v3'
admin_pass: ADMIN_PASS
admin_user: admin
admin_project_name: admin
default_user_domain_name: Default
default_project_domain_name: Default
keystone_region: RegionOne
keystone_identity_api_version: 3
keystone_image_api_version: 2

terraform_dir: /opt/terraform
terraform_user: "{{ ansible_user }}"
terraform_group: "{{ ansible_user }}"
