---
database_user: root
database_pass: overrideme
database_host: "{{ ansible_facts[management_interface]['ipv4']['address'] }}"
database_dir: /var/lib/mysql
database_socket: "{{ _database_socket[ansible_os_family] }}"
_database_socket:
  Debian: /var/run/mysqld/mysqld.sock
  RedHat: /var/lib/mysql/mysql.sock
keystone_user: keystone
keystone_group: keystone
keystone_database: keystone
keystone_database_user: keystone
keystone_database_pass: KEYSTONE_DBPASS
keystone_database_privs: '*.*:ALL'
keystone_database_provider: fernet
keystone_packages:
- openstack-keystone
- httpd
- python3-mod_wsgi

keystone_init_project: default
keystone_init_project_desc: "Service Project"
keystone_init_domain: example
keystone_init_domain_desc: "Example Demo"

keystone_auth_url: 'http://controller:5000/v3'
keystone_admin_pass: ADMIN_PASS
keystone_admin_user: admin
keystone_admin_project_name: admin
keystone_admin_user_domain_name: Default
keystone_admin_project_domain_name: Default
keystone_region: RegionOne
keystone_identity_api_version: 3

terraform_dir: /opt/terraform

keystone_demo_project_name: myproject
keystone_demo_project_desc: "Demo Project"
keystone_demo_project_domain: default
keystone_demo_project_user: myuser
