---
- name: restart mariadb
  service:
    name: mariadb
    state: restarted

- name: restart memcached
  service:
    name: memcached
    state: restarted

- name: restart etcd
  service:
    name: etcd
    state: restarted
