---
controller_hostname: "{{ groups['controller'][0] }}"
keystone_api_url: http://{{ controller_hostname }}:5000
memcached_servers_url: "{{ controller_hostname }}:11211"
database_user: root
database_pass: overrideme
database_host: "{{ hostvars[groups['controller'][0]]['ansible_facts'][management_interface]['ipv4']['address'] }}"
database_dir: /var/lib/mysql
database_socket: "{{ _database_socket[ansible_os_family] }}"
_database_socket:
  Debian: /var/run/mysqld/mysqld.sock
  RedHat: /var/lib/mysql/mysql.sock
placement_user: placement
placement_pass: password123
placement_group: placement
placement_database: placement
placement_database_user: placement
placement_database_pass: PLACEMENT_DBPASS
placement_database_privs: '*.*:ALL'
placement_database_provider: fernet
placement_packages:
- openstack-placement-api

keystone_auth_url: 'http://{{ controller_hostname }}:5000/v3'
admin_pass: ADMIN_PASS
admin_user: admin
admin_project_name: admin
default_user_domain_name: Default
default_project_domain_name: Default
keystone_region: RegionOne
keystone_identity_api_version: 3
keystone_image_api_version: 2

terraform_dir: /opt/terraform
terraform_user: "{{ ansible_user }}"
terraform_group: "{{ ansible_user }}"
