controller_hostname: "{{ groups['controller_hosts'][0] }}"

database_user: root
database_pass: overrideme
database_host: "{{ hostvars[groups['controller_hosts'][0]]['ansible_facts'][management_interface]['ipv4']['address'] }}"
database_dir: /var/lib/mysql
database_socket: "{{ _database_socket[ansible_os_family] }}"
_database_socket:
  Debian: /var/run/mysqld/mysqld.sock
  RedHat: /var/lib/mysql/mysql.sock

keystone_api_url: http://{{ controller_hostname }}:5000
keystone_project_name: service
keystone_auth_type: password
keystone_user: keystone
keystone_group: keystone
keystone_database: keystone
keystone_database_user: keystone
keystone_database_pass: KEYSTONE_DBPASS
keystone_database_privs: '*.*:ALL'
keystone_database_provider: fernet

keystone_init_project: default
keystone_init_project_desc: "Service Project"
keystone_init_domain: example
keystone_init_domain_desc: "Example Demo"
keystone_auth_url: "http://{{ controller_hostname }}:5000/v3"
keystone_identity_api_version: 3

admin_pass: ADMIN_PASS
admin_user: admin
admin_project_name: admin

default_user_domain_name: Default
default_project_domain_name: Default
default_region: RegionOne

image_api_version: 2

demo_project_name: myproject
demo_project_desc: "Demo Project"
demo_project_domain: default
demo_project_user: myuser
demo_project_role: myrole
endpoint_interfaces:
- public
- internal
- admin

glance_service: glance
glance_service_desc: "OpenStack Image"
glance_service_type: image
glance_endpoint_url: "{{ controller_hostname }}:9292"
glance_user: glance
glance_pass: password123
glance_group: glance
glance_database: glance
glance_database_user: glance
glance_database_pass: GLANCE_DBPASS
glance_database_privs: '*.*:ALL'
glance_database_provider: fernet

glance_port: 9292
glance_api_servers: http://{{ controller_hostname }}:{{ glance_port }}

nova_user: nova
nova_pass: password123
nova_group: nova
nova_database: nova
nova_database_api: nova_api
nova_database_cell0: nova_cell0
nova_database_user: nova
nova_database_pass: NOVA_DBPASS
nova_database_provider: fernet
nova_endpoint_url: "{{ controller_hostname }}:8774/v2.1"
nova_service: nova
nova_service_desc: "OpenStack Compute"
nova_service_type: compute


api_auth_strategy: keystone

vnc_enabled: "true"
vnc_server_listen: 0.0.0.0
vnc_server_proxyclient_address: $my_ip
vnc_novncproxy_base_url: http://{{ controller_hostname }}:6080/vnc_auto.html

oslo_concurrency_lock_path: /var/lib/nova/tmp

libvirt_virt_type: qemu

memcached_servers_url: "{{ controller_hostname }}:11211"

placement_user: placement
placement_pass: password123
placement_group: placement
placement_database: placement
placement_database_user: placement
placement_database_pass: PLACEMENT_DBPASS
placement_database_privs: '*.*:ALL'
placement_database_provider: fernet
placement_service: placement
placement_service_desc: "OpenStack Placement"
placement_service_type: placement
placement_endpoint_url: "{{ controller_hostname }}:8778"

etcd_service: etcd
etcd_listen_address: "{{ ansible_facts[management_interface]['ipv4']['address'] }}"

database_root_password: overrideme
database_name: MariaDB
database_service: mariadb

mq_name: RabbitMQ
mq_service: rabbitmq-server
mq_user: openstack
mq_pass: RABBIT_PASS
mq_port: 5672

arch: "{{ _arch[ansible_architecture] }}"
_arch:
  aarch: arm64
  x86_64: amd64
