---
- name: debug playbook
  hosts: controller
  tasks:
  - name: print first controller host
    debug:
      var: hostvars[groups['controller_hosts'][0]]
  - name: print first controller host name
    debug:
      var: groups['controller_hosts'][0]
  - name: print first controller host name
    debug:
      msg: Moin {{ groups['controller_hosts'][0] }}
