---
- name: Create database {{ glance_database }}
  mysql_db:
    name: "{{ glance_database }}"
    login_user: "{{ database_user }}"
    login_password: "{{ database_pass }}"
    login_unix_socket: "{{ database_socket }}"
    state: present

- name: Grant User {{ glance_database_user }} All Privileges on {{ glance_database }}
  mysql_user:
    name: "{{ glance_database_user }}"
    password: "{{ glance_database_pass }}"
    priv: "{{ glance_database_privs }}"
    host: "{{ item }}"
    login_user: "{{ database_user }}"
    login_password: "{{ database_pass }}"
    login_unix_socket: "{{ database_socket }}"
  with_items:
  - localhost
  - '%'
  - "{{ database_host }}"

- name: Get Database Dir Informations
  stat:
    path: "{{ database_dir }}/{{ glance_database }}"
  register: glance_db_dir

- name: Install components
  package:
    name: "{{ glance_packages }}"
    state: present

- name: Configure Glance
  template:
    src: etc/glance/glance-api.conf.j2
    dest: /etc/glance/glance-api.conf
    backup: true
  notify:
  - restart glance-api

- name: Populate the Glance service database
  command: glance-manage db_sync
  become_user: "{{ glance_user }}"
  become: true
  when: glance_db_dir.stat.blocks == 0

- name: Enable Glance API-Service
  service:
    name: openstack-glance-api
    state: started
    enabled: true

- name: Terraform Files
  template:
    src: '{{ item.src }}'
    dest: "{{ terraform_dir }}/{{ item.path | regex_replace('\\.j2$', '') }}"
    owner: "{{ terraform_user }}"
    group: "{{ terraform_group }}"
  with_filetree: '{{ role_path }}/templates/opt/terraform'
  when: item.state == 'file'

  #- name: Run Terraform
  #  terraform:
  #    project_path: "{{ terraform_dir }}"
  #    state: present
  #    binary_path: /usr/local/bin/terraform
  #    force_init: true
  #  become: false
  #  environment:
  #    OS_USERNAME: "{{ admin_user }}"
  #    OS_PASSWORD: "{{ admin_pass }}"
  #    OS_PROJECT_NAME: "{{ admin_project_name }}"
  #    OS_USER_DOMAIN_NAME: "{{ default_user_domain_name }}"
  #    OS_PROJECT_DOMAIN_NAME: "{{ default_project_domain_name }}"
  #    OS_AUTH_URL: "{{ keystone_auth_url }}"
  #    OS_IDENTITY_API_VERSION: "{{ keystone_identity_api_version }}"
  #    OS_IMAGE_API_VERSION: "{{ keystone_image_api_version }}"
